name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  mod:
    name: Mod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.20"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go mod download
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.20"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "--timeout 3m0s"
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.20"
    env:
      GOCACHE: "/tmp/go/cache"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: |-
          go test ./... -race -coverprofile=coverage.txt -shuffle=on
      - name: Upload coverage data
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
  bench:
    name: Bench
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.20"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install cob
        run: curl -sfL https://raw.githubusercontent.com/knqyf263/cob/master/install.sh | sudo sh -s -- -b /usr/local/bin
      - name: Run Benchmark
        run: CGO_ENABLED=0 cob
