name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  mod:
    name: Mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read Go version
        run: echo "GO_VERSION=$(cat ./.go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
      - run: go mod download
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read Go version
        run: echo "GO_VERSION=$(cat ./.go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "--timeout 3m0s"
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOCACHE: "/tmp/go/cache"
    steps:
      - uses: actions/checkout@v3
      - name: Read Go version
        run: echo "GO_VERSION=$(cat ./.go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - uses: actions/cache@v3
        with:
          path: /tmp/go/cache
          key: ${{ runner.os }}-go-build-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ github.ref }}-
            ${{ runner.os }}-go-build-
      - name: Run tests
        run: |-
          # Run race tests (excludes race_test.go)
          go test ./... -race -shuffle=on
          # Upload coverage file on non-race tests
          go test ./... -coverprofile=coverage.txt -shuffle=on
      - name: Upload coverage data
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Read Go version
        run: echo "GO_VERSION=$(cat ./.go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install cob
        run: curl -sfL https://raw.githubusercontent.com/knqyf263/cob/master/install.sh | sudo sh -s -- -b /usr/local/bin
      - name: Run Benchmark
        run: CGO_ENABLED=0 cob
